# Generated by Django 4.2.13 on 2024-06-27 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='master_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 27, 19, 47, 48, 829657)),
        ),
    ]
