# Generated by Django 4.2.13 on 2024-07-04 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_time_master_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='master_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 4, 22, 28, 33, 203805)),
        ),
    ]
